/*
 * Trace Recorder for Tracealyzer v4.11.0
 * Copyright 2025 Percepio AB
 * www.percepio.com
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * The configuration for trace streaming ("stream ports").
 */

#ifndef TRC_STREAM_PORT_CONFIG_H
#define TRC_STREAM_PORT_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @def TRC_CFG_STREAM_PORT_UDP_ADDRESS
 *
 * @brief Defines the host IP address
 */
#ifdef CONFIG_PERCEPIO_TRC_CFG_STREAM_PORT_UDP_IP
#define TRC_CFG_STREAM_PORT_UDP_ADDRESS CONFIG_PERCEPIO_TRC_CFG_STREAM_PORT_UDP_IP
#else
#define TRC_CFG_STREAM_PORT_UDP_ADDRESS "192.168.0.100"
#endif

/**
 * @def TRC_CFG_STREAM_PORT_UDP_PORT
 *
 * @brief Defines the host UDP port
 */
#ifdef CONFIG_PERCEPIO_TRC_CFG_STREAM_PORT_UDP_PORT
#define TRC_CFG_STREAM_PORT_UDP_PORT CONFIG_PERCEPIO_TRC_CFG_STREAM_PORT_UDP_PORT
#else
#define TRC_CFG_STREAM_PORT_UDP_PORT "18419"
#endif

#ifdef CONFIG_PERCEPIO_TRC_CFG_STREAM_PORT_USE_INTERNAL_BUFFER
#define TRC_CFG_STREAM_PORT_USE_INTERNAL_BUFFER 1
/* Aligned */
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_SIZE ((((CONFIG_PERCEPIO_TRC_CFG_INTERNAL_BUFFER_SIZE) + sizeof(TraceUnsignedBaseType_t) - 1) / sizeof(TraceUnsignedBaseType_t)) * sizeof(TraceUnsignedBaseType_t))

#ifdef CONFIG_PERCEPIO_TRC_INTERNAL_EVENT_BUFFER_OPTION_TRANSFER_MODE_CHUNK
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_TRANSFER_MODE TRC_INTERNAL_EVENT_BUFFER_OPTION_TRANSFER_MODE_CHUNKED
/* Aligned */
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_CHUNK_SIZE ((((CONFIG_PERCEPIO_TRC_CFG_INTERNAL_BUFFER_CHUNK_SIZE) + sizeof(TraceUnsignedBaseType_t) - 1) / sizeof(TraceUnsignedBaseType_t)) * sizeof(TraceUnsignedBaseType_t))
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_CHUNK_TRANSFER_AGAIN_SIZE_LIMIT (CONFIG_PERCEPIO_TRC_CFG_INTERNAL_BUFFER_CHUNK_TRANSFER_AGAIN_SIZE_LIMIT)
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_CHUNK_TRANSFER_AGAIN_COUNT_LIMIT (CONFIG_PERCEPIO_TRC_CFG_INTERNAL_BUFFER_CHUNK_TRANSFER_AGAIN_COUNT_LIMIT)
#else
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_TRANSFER_MODE TRC_INTERNAL_EVENT_BUFFER_OPTION_TRANSFER_MODE_ALL
#endif

#else /* CONFIG_PERCEPIO_TRC_CFG_STREAM_PORT_USE_INTERNAL_BUFFER */
#define TRC_CFG_STREAM_PORT_USE_INTERNAL_BUFFER 0
#endif /* CONFIG_PERCEPIO_TRC_CFG_STREAM_PORT_USE_INTERNAL_BUFFER */

#ifdef __cplusplus
}
#endif

#endif /* TRC_STREAM_PORT_CONFIG_H */
